### ISSUE TITLE
error when you start up the server in the console

### ISSUE THREAD

**Issue by HBHC1264** [ArvickC/PunchingSimulator#4]
[11:05:25 INFO]: [PunchSimulator] Disabling PunchSimulator v1.0.1.1

**Comment by ArvickC** [comment]
@HBHC1264 Could you give the full log for the error!

**Comment by ArvickC** [comment]
@HBHC1264 It will look something like [this](https://github.com/ArvickC/McCore/issues/2) (Its in red, appears when server boots up)

**Comment by HBHC1264** [comment]
[latest.log](https://github.com/ArvickC/PunchingSimulator/files/5624416/latest.log)

**Comment by ArvickC** [comment]
```
java.lang.NullPointerException: null
	at me.banana_is_trash.punchsimulator.Files.Data.setup(Data.java:16) ~[?:?]
	at me.banana_is_trash.punchsimulator.PunchSimulator.onEnable(PunchSimulator.java:39) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-288]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
```

**Comment by ArvickC** [comment]
```
	at me.banana_is_trash.punchsimulator.Files.Data.setup(Data.java:16) ~[?:?]
	at me.banana_is_trash.punchsimulator.PunchSimulator.onEnable(PunchSimulator.java:39) ~[?:?]
```

**Comment by HBHC1264** [comment]
?

**Comment by ArvickC** [comment]
Coding stuff, you can see that the error is at:
(Data.java:16) - Data.java file @ line 16
and
(PunchSimulator.java:39) - PunchingSimulator.java file @ line 39

**Comment by HBHC1264** [comment]
so can you fix it? lol why are u telling me

**Comment by ArvickC** [comment]
I'm in school 🤦‍♂️. I can't change it on my phone...

**Comment by HBHC1264** [comment]
oh ill change it

**Comment by ArvickC** [comment]
Do you even know how to fix it?

**Comment by HBHC1264** [comment]
i dont think so

**Comment by ArvickC** [comment]
Just leave it to me, I'll be back home in like 10m

**Comment by HBHC1264** [comment]
oh ok :)

**Comment by ArvickC** [comment]
Error at: [here](https://github.com/ArvickC/PunchingSimulator/blob/master/src/main/java/me/banana_is_trash/punchsimulator/Files/Data.java#L16)

Fix:

Change - `file = new File(Bukkit.getServer().getPluginManager().getPlugin("PunchingSimulator").getDataFolder(), "data.yml");`

To - `file = new File(Bukkit.getServer().getPluginManager().getPlugin("PunchSimulator").getDataFolder(), "data.yml");`
